name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run fix
      - run: yarn run build
      - run: yarn run website-build
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          GIT_CONFIG_NAME: github-actions[bot]
          GIT_CONFIG_EMAIL: github-actions[bot]@users.noreply.github.com
